# Generated by Django 3.1 on 2021-03-17 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
