# Generated by Django 3.1 on 2021-03-04 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('bathroom', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('list_date', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('sqft', models.IntegerField()),
                ('lotsize', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(default=False, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(default=False, upload_to='photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(default=False, upload_to='photos/%Y/%m/%d')),
                ('photo_4', models.ImageField(default=False, upload_to='photos/%Y/%m/%d')),
                ('photo_5', models.ImageField(default=False, upload_to='photos/%Y/%m/%d')),
                ('photo_6', models.ImageField(default=False, upload_to='photos/%Y/%m/%d')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
