# Generated by Django 3.1 on 2021-03-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210305_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
    ]
